### ISSUE TITLE
Center the map where the user is located

### ISSUE THREAD

**Issue by auloin** [oSoc20/WalkByBrussels#13]
Is that possible? Or is it already done? @pietervdvn

**Comment by pietervdvn** [comment]
This is already done. On mobile, an extra button is shown. Upon pressing this, the user is requested to give access to their location; upon clicking again the user is taken to their location.

**Comment by auloin** [comment]
Can't it be implemented on desktop as well?

**Comment by pietervdvn** [comment]
On desktop, this involves sending location data of to a third party (google), which I'd like to avoid.

Furthermore, a user can set a 'home'-location in the OSM-settings; which can be used to go to that location.
