### ISSUE TITLE
Add 'artwork' as POI layer

### ISSUE THREAD

**Issue by pietervdvn** [oSoc20/WalkByBrussels#18]

**Comment by StanIsAdmin** [comment]
Done in 4281b25690d02de40f359e9284c3d2bb38a34dd8

**Comment by pietervdvn** [comment]
Hey Stanislas,

This is already a good first step, but I do not consider this as having added artwork. It shows a pin, but it doesn't offer any interactivity yet.

In `this.elementsToShow`, consider adding a few more options. The first one you'll need to add is `new ImageCarouselWithUploadConstructor()` to add the picture capabilities.

Furthermore, some TagRenderingOptions can be added too. These render a certain aspect (e.g. is this a statue, a mural, ...) or ask a question if the aspect is not known. Have a look in TagRendering.ts on what the options are, and have a look at Bookcases.ts on how to use it. In the [wiki on artwork and tourism](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dartwork), you'll find inspiration on what tags exist. I also already made one earlier but that one wasn't refactored - there too you'll find inspiration.

At last, an icon has to be provided as well that it neatly shows on the map.

**Comment by StanIsAdmin** [comment]
Changed icons, added question about artwork type, added translations for those questions and more on 323a81e
More to come before merging #28 but there is now a styling issue in that branch I will investigate.

**Comment by StanIsAdmin** [comment]
The styling issue was fixed by merging master onto the branch, but because I had to revert a few commits back the PR is now for the "more-osm-layers-**alt**" branch and is #32
